select * from customer limit 20

--Q.1 What is total revenue generated by male vs female customers?
select gender, sum(purchase_amount) as revenue
from customer
group by gender

--Q.2 Which customer used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer 
where discount_applied = 'Yes' and purchase_amount >= (select AVG (purchase_amount) from customer)

--Q.3 Which are the top 5 products with highest review rating?
select item_purchased, AVG(review_rating) as "Average product rating"
from customer 
group by